spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://moo.ctiaim7daspf.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:moon}
    password: ${DB_PASSWORD:03190319}
    driver-class-name: com.mysql.cj.jdbc.Driver