spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}